### ISSUE TITLE
value is unreadable in any redis manager

### ISSUE THREAD

**Issue by Calx-Takeno** [dotnetcore/EasyCaching#117]
I tried Redis Desktop Manager 0.9.3 & 0.8.8, Redis Client, Aonther Redis DeskTop Manager,Redis-cli etc.
Any manager I can find, all tried.
It will show the value like this
����System.Int32m_value�!
or this
\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00\x00\x00\x00\x00\x00\x00\x04\x01\x00\x00\x00\x0cSystem.Int32\x01\x00\x00\x00\am_value\x00\b\b\xe9!\x00\x0b
or nothing in plaintText.
I also tied JSON,XML,HEX. All value is unreadable. It's hard to maintenance.

Redis Verson: 3.2.100

**Comment by catcherwong** [comment]
There are some different between `IEasyCachingProvider` and `IRedisCachingProvider`.

`byte[]` is the main type for `IEasyCachingProvider`, when we use it for redis or memcached, it will serialize `object` to `byte[]` at first, then store the `byte[]` to your cache server. And this is the main reason why the manager tool can not read the value out as plaint text.

`string` is the main type for `IRedisCachingProvider`, due to `IRedisCachingProvider` is special for redis.

**Comment by Calx-Takeno** [comment]
OK. Seem that have to develop special Redis Manager for these format by myself.
Thank you for your response.
