### ISSUE TITLE
Is it available in tranditional desktop .net develop (like WPF)?

### ISSUE THREAD

**Issue by mr-cn** [dotnetcore/EasyCaching#127]
This is a really awesome library, and I was developing for an WPF project.

When installing it, I saw VS informing that the library need some dependencies such as `Microsoft.AspNetCore.Http.Abstractions`.

And the example in README is related to Asp.Net Core, too. 

So, is it a good choice for WPF project?

**Comment by catcherwong** [comment]
@mr-cn  Thanks for your interest in this project.

I am not familiar with desktop develop, but this library is based on `.net standard`, it could be used in both console app and web app.

At this time, it has some dependencies mainly for ASP.NET Core, because too many people develop web apps.  

And I will try to remove them and keep it separated. 😂

**Comment by catcherwong** [comment]
v0.8.0 do not depend on `Microsoft.AspNetCore.Http.Abstractions`.

It should support both ASP.NET Core applications and desktop applications now.
