### ISSUE TITLE
Cache key with prefix generates incorrect cache key

### ISSUE THREAD

**Issue by damianostre** [dotnetcore/EasyCaching#141]
## Description

When _CacheKeyPrefix_ parameter is used an incorrect cache key is generated.
_CacheKeyPrefix_ param value is used instead of _InterfaceName:MethodName_, but should only prefix it.

### Related code

```
public interface ITestService
 {
  [EasyCachingAble(CacheKeyPrefix = "MyPrefix")]
  string Foo(string bar);
}

//Execution
service.Foo("bar");
```

**Expected behavior:**
Generates key: _MyPrefix:ITestService:Foo:bar_

**Actual behavior:**
Generates key: _MyPrefix:bar_

**Comment by catcherwong** [comment]
@damianostre  Thanks for your interest in this project.

Maybe the behavior of key generation is correct because we just make the key format like `Prefix:Params`, and you can follow the UTs for more information.

https://github.com/dotnetcore/EasyCaching/blob/646ef2a9f5237f00b602339ecc15e5863637f324/test/EasyCaching.UnitTests/Core/DefaultEasyCachingKeyGeneratorTest.cs#L97-L119

If you want to change the default behavior of this one, you can create a PR to do this. 😄

**Comment by damianostre** [comment]
@catcherwong understood :) It's just a bit misleading as it's actually not a prefix, but main part of the key. Prefixes is a cool mechanism for grouping keys to easy invalidating them later.

Anyway, thanks for a great project!
