### ISSUE TITLE
Expiration time of key

### ISSUE THREAD

**Issue by Mcgrady2009** [dotnetcore/EasyCaching#215]
## Description
How not to set expiration time for key
[key ]
Using TimeSpan.Zero throws an exception

**Comment by catcherwong** [comment]
@Mcgrady2009 Thanks for your interest in this project.

`IEasyCachingProvider` must set a value greater than 0. If you use Redis, `IRedisProvider` can not set 
 expiration. 

cc #90

**Comment by Mcgrady2009** [comment]
Thanks a lot

**Comment by xsoheilalizadeh** [comment]
@catcherwong,
I think we should support not setting the expiration key, I'm using hybrid caching with Redis and InMemory and I have a case where not having the expiration key is very critical because of the Redis eviction policy, our instance is using `volatile-lru` and in order to prevent our keys to be removed we have to be abe to set the keys without a TTL.

**Comment by xsoheilalizadeh** [comment]
@catcherwong I can look into this if you are not working on it.
