### ISSUE TITLE
能否暴露缓存项的过期时间

### ISSUE THREAD

**Issue by wujunchengman** [dotnetcore/EasyCaching#331]
我有一个缓存需要刷新过期时间，但是它的访问可能非常频繁，我想只有到过期时间一定间隔内刷新，而不是只能在每次访问时都去重新Set过期时间，请问这样的可以吗？

**Comment by catcherwong** [comment]
@wujunchengman Thanks for your interest in this project.

At this time, EasyCaching only supports absolute expiration, does not support relative expiration.

Two suggestion here:

1. If the cached value will not be modified frequently, try to increase the expiration.
2. Try to refresh regularly instead of calling the set method every time.

-----------

现阶段，EasyCaching只支持绝对过期时间，还不支持相对过期时间。

针对您的问题，有两个处理建议：

1. 如果缓存不会频繁的修改，考虑增加过期时间
2. 尝试用定时延期的方式，而不是每次都重新set

**Comment by catcherwong** [comment]
https://github.com/dotnetcore/EasyCaching/blob/c842bfe2bc1fabd40e3e781516e1bfb57bfb89fe/src/EasyCaching.Core/IEasyCachingProvider.cs#L99-L111

`GetExpiration/ GetExpirationAsync ` can get the expiration of the cached value.

--------

`GetExpiration/ GetExpirationAsync `  可以获取到这个缓存项的过期时间.
